import uuid
from typing import List

from pydantic import BaseModel, Field

class DatiRecordC2Model(BaseModel):
    uuid: str = Field(default_factory=lambda: str(uuid.uuid4()))
    regione_addebitante: str = Field(..., max_length=3)
    az_osp_inviante: str = Field(..., max_length=3)
    codice_struttura_erogatrice: str = Field(..., max_length=6)
    numero_ricetta: str = Field(..., max_length=16)
    progressivo_riga_per_ricetta: str = Field(..., max_length=2)
    data: str = Field(..., max_length=8)
    codifica_nomenclatore: str = Field(..., max_length=1)
    codice_prestazione: str = Field(..., max_length=7)
    quantita: str = Field(..., max_length=3)
    posizione_dell_utente_nei_confronti_del_ticket: str = Field(..., max_length=2)
    importo_ticket: str = Field(..., max_length=7)
    importo_totale: str = Field(..., max_length=8)
    posizione_contabile: str = Field(..., max_length=1)
    errori_anagrafici: str = Field(..., max_length=1)
    errori_residenza: str = Field(..., max_length=1)
    errori_prestazione: str = Field(..., max_length=1)
    errori_ricetta: str = Field(..., max_length=1)
    errori_record: str = Field(..., max_length=1)
    errori_importo: str = Field(..., max_length=1)
    errori_quantita: str = Field(..., max_length=1)
    errori_data_prestazione: str = Field(..., max_length=1)
    errori_ricetta_2: str = Field(..., max_length=1)
    errore_riservato: str = Field(..., max_length=1)
    id: str = Field(..., max_length=20)
    regione_iniziale_addebito: str = Field(..., max_length=3)
    tipo_erogazione: str = Field(..., max_length=2)
    codice_disciplina_unita_operativa_erogatrice: str = Field(..., max_length=3)
    classe_priorita_prenotazione: str = Field(..., max_length=1)
    codice_esenzione: str = Field(..., max_length=6)
    tipo_struttura: str = Field(..., max_length=1)
    quota_compartecipazione_alla_spesa: str = Field(..., max_length=8)
    fatturato_al_lordo_ticket: str = Field(..., max_length=8)
    campo_vuoto: str = Field(..., max_length=8)
    numero_fattura: str = Field(..., max_length=20)
    data_fattura: str = Field(..., max_length=8)
    fatturato_al_netto_ticket: str = Field(..., max_length=8)
    liquidato:str = Field(..., max_length=8)
    causa_mancata_liquidazione: str = Field(..., max_length=1)
    causa_parziale_liquidazione: str = Field(..., max_length=1)
    # codice_prestazione_cur: str = Field(..., max_length=8)
    # branca_specialistica:str = Field(..., max_length=2)
    garanzia_tempi_massimi: str = Field(..., max_length=1)
    numero_sedute_cliniche: str = Field(..., max_length=3)
    data_prenotazione: str = Field(..., max_length=8)
    data_prima_disponibilita: str = Field(..., max_length=8)
    data_primo_appuntamento: str = Field(..., max_length=8)
    tipo_prestazione: str = Field(..., max_length=1)



class DatiFileC2Model(BaseModel):
    records: List[DatiRecordC2Model] = Field(default_factory=list)
    nome_file: str = Field(default="")